### PR TITLE
Correctly handle fractional positions when rebalancing

### PR DESCRIPTION
**Pull request by ran404**
hey @pmorissette,

I found a bug (this may have been discussed in an earlier issue but I can't seem to find it) in bt related to the using non-integer positions. Basically, when the use_integer_positions flag is set to false, sometimes the allocation value for individual securities are off by a single share. The bit of code that does this is line 1074 in core.py. It looks like the assumption here is that q should always decrement by 1. But in the cases of decimal shares, due to floating point approximation issues, even when full_outlay should be theoretically exactly equal to amount, the condition "full_outlay > amount" might evaluate to true, hence causing the undesired effect of buying one less whole share.
```python
            while full_outlay > amount and q != 0:
                q = q - 1
```

This can be easily reproduced with the following unit tests (the sum of individual securities do not add up):
```python
def test_strategybase_tree_decimal_position_rebalance():
    c1 = SecurityBase('c1')
    c2 = SecurityBase('c2')
    s = StrategyBase('p', [c1, c2])
    s.use_integer_positions(False)

    c1 = s['c1']
    c2 = s['c2']

    dts = pd.date_range('2010-01-01', periods=3)
    data = pd.DataFrame(index=dts, columns=['c1', 'c2'], data=100)

    s.setup(data)

    i = 0
    s.update(dts[i], data.ix[dts[i]])

    s.adjust(1000.2)
    s.rebalance(0.42, 'c1')
    s.rebalance(0.58, 'c2')

    aae(c1.value, 420.084)
    aae(c2.value, 580.116)
    aae(c1.value + c2.value, 1000.2)
```

I'm proposing we fix this with the following bit of code:
```python
                if self.integer_positions:
                    q_delta = 1
                else:
                    q_delta = min(1., (full_outlay - amount) / self._price)
                q = q - q_delta
```

so if we are using integer_positions (default case), then decrement a single share as usual, otherwise we decrement by the smallest of either 1 share or a fractional q. In cases where the the condition gets hit due to floating point approximation issues, the above should code should be able to break out in a single iteration, and we get a correct decimal quantity.

What do you think? There may be a cleaner way to handle this!

BTW - would it be possible to add automated CI, such as Travis? It would be good to know from a glance  if all the tests are passing.

### CODE REVIEW

**Comment by FinQuest** [comment]
Is it similar to https://github.com/pmorissette/bt/issues/97?

**Comment by ran404** [comment]
Yes, #97 describes the very issue. I can see that it's rather tricky given the need to accommodate calculation of commissions.

**Comment by magnumw** [comment]
@ran404 thanks so much. solved my issue.

**Comment by JordanPlatts** [comment]
I didn't realize someone else had already proposed a fix to the floating point issue #137  until after I added my own fix.

My fix was to add a condition on the while loop where it checked if `full_outlay` and `amount` were close.

     while not np.isclose(full_outlay,amount,rtol=0.) and full_outlay > amount and q != 0:

I set relative tolerance to 0. because it didn't seem to help. If they are within 1e-08 to each other, then they are declared equal.

Please let me know if this doesn't seem adequate or if there is a test case where this fails.

[numpy.isclose documentation](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.isclose.html)

I also separately added Travis which is funny because I didn't realize it was already proposed until after I read this thread.

**Comment by ran404** [comment]
Hi this looks like a cleaner solution than my fix a while back. If the unit test that I added passes (test_strategybase_tree_decimal_position_rebalance) then I say it’s good to go with your numpy.isclose version. Thanks.

**Pull request merged**
