### PR TITLE
Integration with Codecov 

### PR DESCRIPTION
**Pull request by FinQuest**
Think this would complement some of great work @JordanPlatts  has been doing over past couple of week!

Appreciate would require additional effort to open [codecov](https://codecov.io/) account.

### CODE REVIEW

**Comment by JordanPlatts** [comment]
I appreciate the comment. So a codecov account needs to be opened?

**Comment by FinQuest** [comment]
Correct. It would require account and some minor config but quite quick (similar to Travis)

Let me know if I can help and can raise equivalent for ffn if this helps.

**Comment by JordanPlatts** [comment]
It seems to work. The badge is showing 76% coverage. I don't really know how.... Either way it seems like a nice tool.

@pmorissette can you open an account on [codcov](https://codecov.io/)?

**Comment by FinQuest** [comment]
Not sure where that number comes from either with no a/c...

**Pull request merged**
